const constant = {}


// REGISTRATION
constant.REGISTER_SOCMED = 'REGISTER_SOCMED'
constant.REGISTER_PHONE = 'REGISTER_PHONE'
constant.REGISTER_TOKEN = 'REGISTER_TOKEN'
constant.REGISTER_NAME = 'REGISTER_NAME'
constant.REGISTER_USERNAME = 'REGISTER_USERNAME'
constant.CLEAN_REGISTRATION = 'CLEAN_REGISTRATION'
constant.REGISTRATION = 'REGISTRATION'
constant.SET_CAMPAIGN = 'SET_CAMPAIGN'

// AUTH
constant.LOGIN = 'LOGIN'
constant.LOGOUT = 'LOGOUT'

// NOTIFICATION
constant.SET_NOTIFICATION = 'SET_NOTIFICATION'
constant.ADD_NOTIFICATION = 'ADD_NOTIFICATION'
constant.CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

// PROFILE
constant.PROFILE_UPDATE = 'PROFILE_UPDATE'
constant.SET_ADDRESS = 'SET_ADDRESS'
constant.AVATAR_UPDATE = 'AVATAR_UPDATE'
constant.SET_LANGUAGE = 'SET_LANGUAGE'


export default constant;